folio-org/stripes-final-form

translations/stripes-final-form/ar.json, translations/stripes-final-form/ca.json, translations/stripes-final-form/da.json, translations/stripes-final-form/de.json, translations/stripes-final-form/en_GB.json, translations/stripes-final-form/en_SE.json, translations/stripes-final-form/es.json, translations/stripes-final-form/es_419.json, translations/stripes-final-form/es_ES.json, translations/stripes-final-form/fr.json, translations/stripes-final-form/fr_FR.json, translations/stripes-final-form/hu.json, translations/stripes-final-form/it_IT.json, translations/stripes-final-form/pt_BR.json, translations/stripes-final-form/pt_PT.json, translations/stripes-final-form/zh_CN.json
=> Update translation strings as of 20190801T134041

translations/stripes-final-form/pt_BR.json
=> Update translation strings as of 20190802T183501

translations/stripes-final-form/it_IT.json
=> Update translation strings as of 20190823T083240

translations/stripes-final-form/zh_CN.json
=> Update translation strings as of 20190909T193700

translations/stripes-final-form/ru.json, translations/stripes-final-form/zh_TW.json
=> Update translation strings as of 20191014T135140

translations/stripes-final-form/ja.json
=> Update translation strings as of 20191028T205642

translations/stripes-final-form/ru.json
=> Update translation strings as of 20191111T233434

translations/stripes-final-form/ru.json
=> Update translation strings as of 20191113T152522

translations/stripes-final-form/he.json
=> Update translation strings as of 20191113T214202

translations/stripes-final-form/fr_FR.json
=> Update translation strings as of 20191122T140350

translations/stripes-final-form/fr_FR.json
=> Update translation strings as of 20191127T181804

translations/stripes-final-form/fr_FR.json
=> Update translation strings as of 20191209T142332

translations/stripes-final-form/es_ES.json
=> Update translation strings as of 20191216T200945

translations/stripes-final-form/es.json, translations/stripes-final-form/es_419.json
=> Update translation strings as of 20191220T210632

translations/stripes-final-form/fr.json
=> Update translation strings as of 20200127T144839

translations/stripes-final-form/ur.json
=> Update translation strings as of 20200210T220102

lib/StripesFinalFormWrapper.js, package.json
- Fulfills [STRIPESFF-1](https://issues.folio.org/browse/STRIPESFF-1)
- Updated eslint to 6.2.1
- Fixed small eslint errors
=> Stripes 648

lib/StripesFinalFormWrapper.js
Add missing prop type. Thanks @maximdidenkoepam for catching this!
=> Add missing prop

CHANGELOG.md, lib/StripesFinalFormWrapper.js
https://issues.folio.org/browse/STRIPESFF-3
=>  STRIPESFF-3: Turn off navigation check during submission. 

translations/stripes-final-form/ja.json
=> Update translation strings as of 20200415T223222

translations/stripes-final-form/zh_TW.json
=> Update translation strings as of 20200505T210535

CHANGELOG.md, package.json
[STRIPES-672](https://issues.folio.org/browse/STRIPES-672)
=> STRIPES-672 react-intl 4.5

translations/stripes-final-form/zh_TW.json
=> Update translation strings as of 20200513T135229

translations/stripes-final-form/hi_IN.json, translations/stripes-final-form/ja.json, translations/stripes-final-form/ko.json
=> Update translation strings as of 20200921T192032

translations/stripes-final-form/ja.json, translations/stripes-final-form/pl.json
=> Update translation strings as of 20200924T211627

translations/stripes-final-form/ber.json
=> Update translation strings as of 20201109T135508

translations/stripes-final-form/de.json
=> Update translation strings as of 20201119T214636

CHANGELOG.md, package.json
Increment `react` to `v17`.
Refs [STRIPESFF-10](https://issues.folio.org/browse/STRIPESFF-10), [STRIPES-722](https://issues.folio.org/browse/STRIPES-722)
=> STRIPESFF-10 react v17

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, package.json
Refs [STRIPESFF-16](https://issues.folio.org/browse/STRIPESFF-16)
=> STRIPESFF-16 upgrade NodeJS to active LTS, v16

CHANGELOG.md, lib/StripesFinalFormWrapper.js, package.json
https://issues.folio.org/browse/STRIPESFF-27
=> STRIPESFF-27: Avoid private paths in stripes-core imports

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml, CHANGELOG.md, package.json
Refs [STRIPESFF-29](https://issues.folio.org/browse/STRIPESFF-29)
=> STRIPESFF-29 compile translations

.github/CODEOWNERS
Refs [STRIPESFF-40](https://folio-org.atlassian.net/browse/STRIPESFF-40)
=> STRIPESFF-40 implement CODEOWNERS
